# -*- coding: utf-8 -*-
"""ner/ner_extractor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNFFNATwEPf2KIEu-awSYeI5xe8hp0cU
"""

# ner/ner_extractor.py

"""
BERT-based Named Entity Recognizer
------------------------------------
Uses HuggingFace's pretrained NER pipeline built on BERT.

Model: dbmdz/bert-large-cased-finetuned-conll03-english
  - Trained on CoNLL-2003 NER benchmark dataset
  - Recognizes 4 entity types:
      PER  → Person names       (e.g., "Isaac Newton")
      ORG  → Organizations      (e.g., "MIT", "Google")
      LOC  → Locations          (e.g., "Paris", "India")
      MISC → Miscellaneous      (e.g., "English", "Olympics")

How BERT NER works:
  1. Tokenize sentence into subword tokens
  2. BERT reads ALL tokens simultaneously (bidirectional)
  3. For each token → predict entity label (B-PER, I-PER, O, etc.)
  4. Merge subword tokens back into full words

B- prefix = Beginning of entity  ("B-PER" = first token of a person name)
I- prefix = Inside entity         ("I-PER" = continuation of person name)
O  label  = Outside (not entity)
"""

from transformers import pipeline
import re


# ── Entity type mapping ─────────────────────────────────────────
# Map BERT's labels to human-friendly names + emojis
ENTITY_TYPE_MAP = {
    "PER"  : ("PERSON",       "👤"),
    "ORG"  : ("ORGANIZATION", "🏢"),
    "LOC"  : ("LOCATION",     "📍"),
    "MISC" : ("MISCELLANEOUS","🔖"),
}

# Global pipeline instance (load once, reuse)
_ner_pipeline = None


def get_ner_pipeline():
    """
    Loads the BERT NER pipeline (only once).

    Uses lazy loading — model loads on first call,
    then stays in memory for fast subsequent calls.

    Returns:
        HuggingFace NER pipeline object
    """
    global _ner_pipeline

    if _ner_pipeline is None:
        print("[NER] Loading BERT NER model (first time ~30 seconds)...")

        _ner_pipeline = pipeline(
            task  = "ner",

            # Pretrained BERT fine-tuned on CoNLL-2003 NER task
            model = "dbmdz/bert-large-cased-finetuned-conll03-english",

            # aggregation_strategy="simple" automatically merges
            # subword tokens like ["Albert", "Ein", "##stein"]
            # back into "Albert Einstein" ✅
            aggregation_strategy = "simple",
        )
        print("[NER] BERT NER model loaded! ✅")

    return _ner_pipeline


def extract_entities(text: str) -> dict:
    """
    Extracts named entities from a text string.

    Args:
        text (str): Any text — a sentence, paragraph, or full document

    Returns:
        dict: Organized entities by type
              {
                "PERSON":       ["Albert Einstein", "Marie Curie"],
                "ORGANIZATION": ["MIT", "Google"],
                "LOCATION":     ["Paris", "New Jersey"],
                "MISCELLANEOUS":["English", "Nobel Prize"]
              }
    """

    if not text or not text.strip():
        return {"PERSON": [], "ORGANIZATION": [], "LOCATION": [], "MISCELLANEOUS": []}

    ner = get_ner_pipeline()

    # HuggingFace NER has a max token limit (~512 tokens)
    # For long texts, we process in chunks
    chunks = _split_into_chunks(text, max_chars=400)

    # Collect all raw entity predictions across chunks
    all_raw_entities = []
    for chunk in chunks:
        if chunk.strip():
            raw = ner(chunk)
            all_raw_entities.extend(raw)

    # Organize entities into clean categories
    organized = _organize_entities(all_raw_entities)

    return organized


def _split_into_chunks(text: str, max_chars: int = 400) -> list:
    """
    Splits long text into smaller chunks for BERT processing.

    BERT has a 512-token limit. We split on sentence boundaries
    to avoid cutting words mid-sentence.

    Args:
        text (str): Full document text
        max_chars (int): Max characters per chunk

    Returns:
        list: List of text chunk strings
    """
    # Split on sentence endings
    sentences = re.split(r'(?<=[.!?])\s+', text)

    chunks   = []
    current  = ""

    for sentence in sentences:
        # If adding this sentence keeps us under the limit, add it
        if len(current) + len(sentence) < max_chars:
            current += " " + sentence
        else:
            # Save current chunk and start a new one
            if current.strip():
                chunks.append(current.strip())
            current = sentence

    # Don't forget the last chunk
    if current.strip():
        chunks.append(current.strip())

    return chunks


def _organize_entities(raw_entities: list) -> dict:
    """
    Converts raw HuggingFace output into a clean organized dict.

    Raw output looks like:
    [
      {"entity_group": "PER", "word": "Albert Einstein", "score": 0.998},
      {"entity_group": "LOC", "word": "New Jersey",      "score": 0.991},
      ...
    ]

    Args:
        raw_entities (list): Raw output from HuggingFace NER pipeline

    Returns:
        dict: Clean {entity_type: [entity_strings]} dictionary
    """

    organized = {
        "PERSON"        : [],
        "ORGANIZATION"  : [],
        "LOCATION"      : [],
        "MISCELLANEOUS" : [],
    }

    seen = set()  # Track duplicates

    for entity in raw_entities:
        entity_group = entity.get("entity_group", "")
        word         = entity.get("word", "").strip()
        score        = entity.get("score", 0.0)

        # Only accept high-confidence predictions (above 80%)
        if score < 0.80:
            continue

        # Clean up BERT artifacts
        # BERT sometimes produces "##suffix" tokens — remove them
        word = re.sub(r"##", "", word).strip()

        # Skip very short or already-seen entities
        if len(word) < 2 or word.lower() in seen:
            continue

        # Map entity group to our organized categories
        if entity_group == "PER":
            organized["PERSON"].append(word)
        elif entity_group == "ORG":
            organized["ORGANIZATION"].append(word)
        elif entity_group == "LOC":
            organized["LOCATION"].append(word)
        elif entity_group == "MISC":
            organized["MISCELLANEOUS"].append(word)

        seen.add(word.lower())  # Mark as seen

    return organized


def format_entities_for_display(entities: dict) -> str:
    """
    Formats extracted entities into a readable string for display
    in the Streamlit UI or terminal output.

    Args:
        entities (dict): Output from extract_entities()

    Returns:
        str: Nicely formatted multi-line string
    """

    lines = ["📌 **Extracted Named Entities**\n"]

    total = sum(len(v) for v in entities.values())

    if total == 0:
        return "No named entities found in this text."

    for entity_type, words in entities.items():
        if not words:
            continue

        # Get emoji for this entity type
        # Find matching key in ENTITY_TYPE_MAP
        emoji = "🔖"  # default
        for key, (name, em) in ENTITY_TYPE_MAP.items():
            if name == entity_type:
                emoji = em
                break

        lines.append(f"{emoji} **{entity_type}** ({len(words)} found):")
        for word in words:
            lines.append(f"   • {word}")
        lines.append("")  # Blank line between groups

    lines.append(f"Total entities found: {total}")
    return "\n".join(lines)


def extract_entities_from_sentences(sentences: list) -> list:
    """
    Runs NER on each sentence individually and returns
    a list of (sentence, entities) pairs.

    Useful for the Streamlit UI to show which sentence
    each entity came from.

    Args:
        sentences (list): List of sentence strings

    Returns:
        list: [ (sentence_str, entities_dict), ... ]
    """

    results = []
    ner     = get_ner_pipeline()

    for sentence in sentences:
        if not sentence.strip():
            continue

        raw      = ner(sentence)
        entities = _organize_entities(raw)

        # Only include sentences that actually have entities
        total = sum(len(v) for v in entities.values())
        if total > 0:
            results.append((sentence, entities))

    return results