# -*- coding: utf-8 -*-
"""ner/test_ner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sINBEtl_Ge2WrNucB9JvpOsBElqOqjOc
"""

# ner/test_ner.py
# Run: python -m ner.test_ner

"""
NER Test Script
----------------
Tests the BERT NER extractor on sample study text.
"""

from ner.ner_extractor import (
    extract_entities,
    format_entities_for_display,
    extract_entities_from_sentences
)

# ── Test 1: Science notes ────────────────────────────────────────
print("\n" + "="*60)
print("TEST 1: Science Study Notes")
print("="*60)

science_text = """
Albert Einstein developed the theory of relativity in 1905.
Isaac Newton formulated the laws of motion at Cambridge University.
Marie Curie was the first woman to win the Nobel Prize.
Stephen Hawking conducted research at the University of Oxford.
NASA launched the Hubble Space Telescope from Cape Canaveral.
"""

entities = extract_entities(science_text)
print(format_entities_for_display(entities))


# ── Test 2: Computer Science notes ──────────────────────────────
print("\n" + "="*60)
print("TEST 2: Computer Science Notes")
print("="*60)

cs_text = """
Alan Turing worked at Bletchley Park during World War II.
Google developed TensorFlow as an open-source ML framework.
Yann LeCun at Meta AI pioneered Convolutional Neural Networks.
Geoffrey Hinton won the Turing Award for his work on deep learning.
The Python programming language was created by Guido van Rossum.
Stanford University and MIT are leading AI research institutions.
"""

entities = extract_entities(cs_text)
print(format_entities_for_display(entities))


# ── Test 3: Per-sentence extraction ─────────────────────────────
print("\n" + "="*60)
print("TEST 3: Per-Sentence Entity Extraction")
print("="*60)

sentences = [
    "Albert Einstein developed the theory of relativity.",
    "Neural networks are inspired by the human brain.",
    "Google and Microsoft are major AI companies.",
    "Backpropagation is used to train deep networks.",
    "Paris is the capital of France.",
]

results = extract_entities_from_sentences(sentences)

for sentence, entities in results:
    print(f"\n📝 Sentence: '{sentence}'")
    for etype, words in entities.items():
        if words:
            print(f"   {etype}: {', '.join(words)}")

print("\n✅ NER tests complete!")