# -*- coding: utf-8 -*-
"""embeddings/one_hot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vce7cS5xdaxj2rL2RvFVr7IqkQ-XN_Cb
"""

# embeddings/one_hot.py

"""
One-Hot Encoding
----------------
The simplest text representation method.

Pros:
  ✅ Easy to understand and implement
  ✅ No training required

Cons:
  ❌ Vocabulary can be huge (10,000+ words = 10,000-dim vectors!)
  ❌ No semantic meaning ("cat" and "kitten" look totally different)
  ❌ Sparse — mostly zeros, wastes memory

Use case: Good for learning/demos, NOT for real NLP tasks.
For real tasks, always use Sentence Transformers (next file).
"""

import numpy as np


def build_vocabulary(token_lists: list) -> dict:
    """
    Builds a vocabulary dictionary from a list of token lists.

    Args:
        token_lists (list): List of token lists
                           e.g., [["cat","sat","mat"], ["dog","ran","fast"]]

    Returns:
        dict: {word: index} mapping
              e.g., {"cat": 0, "sat": 1, "mat": 2, "dog": 3, ...}
    """
    vocab = {}
    index = 0

    for tokens in token_lists:
        for token in tokens:
            if token not in vocab:
                vocab[token] = index
                index += 1

    print(f"[ONE-HOT] Vocabulary size: {len(vocab)} words")
    return vocab


def one_hot_encode(tokens: list, vocab: dict) -> np.ndarray:
    """
    Converts a list of tokens into a one-hot encoded matrix.

    Each row = one token
    Each column = one vocabulary word
    Value = 1 if present, 0 if absent

    Args:
        tokens (list): List of word tokens for one sentence
        vocab (dict): The vocabulary {word: index}

    Returns:
        np.ndarray: Matrix of shape (num_tokens, vocab_size)
    """
    vocab_size = len(vocab)
    # Create a matrix of zeros: rows=tokens, cols=vocab
    matrix = np.zeros((len(tokens), vocab_size), dtype=int)

    for row_idx, token in enumerate(tokens):
        if token in vocab:
            col_idx = vocab[token]
            matrix[row_idx][col_idx] = 1  # Mark presence with 1
        # If word not in vocab, row stays all zeros (unknown word)

    return matrix


def sentence_to_bow(tokens: list, vocab: dict) -> np.ndarray:
    """
    Bag of Words (BoW) — a simpler version of one-hot.

    Instead of per-word rows, BoW gives ONE vector per sentence
    where each value = how many times that word appears.

    Example:
      Sentence: "the cat sat on the mat"
      Tokens:   ["cat", "sat", "mat", "the", "the"]
      BoW:      [0, ..., 2(the), 1(cat), 1(sat), 1(mat), ...]

    Args:
        tokens (list): Tokens for one sentence
        vocab (dict): Vocabulary {word: index}

    Returns:
        np.ndarray: Single vector of shape (vocab_size,)
    """
    vector = np.zeros(len(vocab), dtype=int)

    for token in tokens:
        if token in vocab:
            vector[vocab[token]] += 1  # Count occurrences

    return vector


def demo_one_hot():
    """Quick demo to visualize one-hot encoding."""

    sentences = [
        ["machine", "learning", "powerful"],
        ["deep", "learning", "neural", "network"],
        ["machine", "network", "data"]
    ]

    # Build vocabulary from all sentences
    vocab = build_vocabulary(sentences)
    print(f"\nVocabulary: {vocab}\n")

    # Encode first sentence
    encoded = one_hot_encode(sentences[0], vocab)
    print(f"One-Hot for {sentences[0]}:")
    print(encoded)

    # Bag of Words for first sentence
    bow = sentence_to_bow(sentences[0], vocab)
    print(f"\nBag-of-Words for {sentences[0]}:")
    print(bow)
```

---

## 📄 File 2: `embeddings/sentence_embeddings.py`

### 💡 What are Sentence Transformers?
A **pretrained deep learning model** that converts entire sentences into dense vectors of **384 or 768 numbers** — capturing actual semantic meaning.
```
"The cat sat on the mat"   → [0.23, -0.45, 0.78, ...]
"A kitten rested on a rug" → [0.21, -0.43, 0.75, ...]  ← Very similar! ✅
"Quantum physics is hard"  → [-0.91, 0.34, -0.12, ...] ← Very different ✅