# -*- coding: utf-8 -*-
"""embeddings/test_embeddings

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gCPQBYNi1CX8kCxzHJeVq73K9wH_1pVs
"""

# embeddings/test_embeddings.py
# Run: python -m embeddings.test_embeddings

from embeddings.one_hot import build_vocabulary, one_hot_encode, demo_one_hot
from embeddings.sentence_embeddings import embed_sentences, find_most_similar

print("=" * 50)
print("TEST 1: One-Hot Encoding Demo")
print("=" * 50)
demo_one_hot()

print("\n" + "=" * 50)
print("TEST 2: Sentence Transformer Embeddings")
print("=" * 50)

sentences = [
    "Neural networks are inspired by the human brain.",
    "Deep learning uses multiple hidden layers.",
    "The mitochondria is the powerhouse of the cell.",
    "Photosynthesis converts sunlight into energy.",
    "Backpropagation trains neural networks using gradients.",
]

embeddings = embed_sentences(sentences)
print(f"\nEmbedding shape: {embeddings.shape}")
print(f"First vector (first 5 values): {embeddings[0][:5]}")

print("\n" + "=" * 50)
print("TEST 3: Semantic Search")
print("=" * 50)

query = "How do neural networks learn?"
print(f"\nQuery: '{query}'")
print("\nTop 3 most relevant sentences:")

results = find_most_similar(query, sentences, top_n=3)
for i, (sentence, score) in enumerate(results, 1):
    print(f"  {i}. [Score: {score}] {sentence}")