# -*- coding: utf-8 -*-
"""CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2NS_8PIFm9nnX5QZmPcR7WTO4VOjpvU
"""

# models/cnn_model.py

"""
CNN — Convolutional Neural Network for Text Classification
-----------------------------------------------------------
In images, CNNs detect edges and shapes.
In text, CNNs detect local patterns like:
  - "is defined as" → Definition signal
  - "for example"   → Example signal
  - "it is crucial" → Important point signal

Architecture:
  Input (1, 384) → Conv1D filters → MaxPool → Flatten → Dense → Output(4)

We treat the 384-dim embedding as a 1D "signal"
and apply convolutional filters across it.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np


class CNNClassifier(nn.Module):

    def __init__(self, input_dim: int = 384, num_classes: int = 4):
        super(CNNClassifier, self).__init__()

        # ── Convolutional Block ───────────────────────────────────
        # in_channels=1  (we treat embedding as 1 channel)
        # out_channels=64 (learn 64 different filters)
        # kernel_size=3  (each filter looks at 3 values at a time)
        self.conv_block = nn.Sequential(
            nn.Conv1d(in_channels=1, out_channels=64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2),  # Halves the sequence length

            nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2),  # Halves again
        )

        # Calculate the flattened size after convolutions
        # 384 → /2 → 192 → /2 → 96  (with 128 channels)
        conv_output_size = (input_dim // 4) * 128

        # ── Fully Connected Block ─────────────────────────────────
        self.fc_block = nn.Sequential(
            nn.Flatten(),
            nn.Linear(conv_output_size, 128),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(128, num_classes)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x shape: (batch_size, 384)
        We add a channel dimension: (batch_size, 1, 384)
        """
        x = x.unsqueeze(1)        # Add channel dim: (B, 384) → (B, 1, 384)
        x = self.conv_block(x)    # Conv layers
        x = self.fc_block(x)      # Dense layers
        return x


def train_cnn(X_train, y_train, X_val, y_val,
              epochs: int = 50, lr: float = 0.001) -> tuple:
    """Trains the CNN model — same structure as ANN trainer."""

    X_train_t = torch.FloatTensor(X_train)
    y_train_t = torch.LongTensor(y_train)
    X_val_t   = torch.FloatTensor(X_val)
    y_val_t   = torch.LongTensor(y_val)

    train_loader = DataLoader(
        TensorDataset(X_train_t, y_train_t),
        batch_size=16, shuffle=True
    )

    model     = CNNClassifier()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    train_losses, val_losses = [], []

    print(f"\n[CNN] Training for {epochs} epochs...")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0

        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            outputs = model(X_batch)
            loss    = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_train_loss = epoch_loss / len(train_loader)
        train_losses.append(avg_train_loss)

        model.eval()
        with torch.no_grad():
            val_loss = criterion(model(X_val_t), y_val_t).item()
            val_losses.append(val_loss)

        if (epoch + 1) % 10 == 0:
            print(f"  Epoch [{epoch+1}/{epochs}] "
                  f"Train Loss: {avg_train_loss:.4f} | Val Loss: {val_loss:.4f}")

    print("[CNN] Training complete! ✅")
    return model, train_losses, val_losses