# -*- coding: utf-8 -*-
"""Data Prep and ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MH42wtMo8xh3WWs-qT18bHiPay6GpN95
"""

!pip install torch scikit-learn sentence-transformers pandas

import os
os.makedirs("models", exist_ok=True)
os.makedirs("embeddings", exist_ok=True)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile embeddings/sentence_embeddings.py
# from sentence_transformers import SentenceTransformer
# 
# model = SentenceTransformer('all-MiniLM-L6-v2')
# 
# def embed_sentences(sentences):
#     return model.encode(sentences)

# models/data_prep.py

"""
Training Data Preparation
--------------------------
Creates a labeled dataset for sentence classification.

Labels:
  0 = Definition
  1 = Concept
  2 = Example
  3 = Important Point

In a real project you'd use a large dataset (CSV/JSON).
Here we create a solid starter set + show how to load from CSV.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from embeddings.sentence_embeddings import embed_sentences

# ── Label mapping ───────────────────────────────────────────────
LABEL_MAP = {
    "definition"      : 0,
    "concept"         : 1,
    "example"         : 2,
    "important_point" : 3
}

# Reverse map for converting predictions back to names
ID_TO_LABEL = {v: k for k, v in LABEL_MAP.items()}


# ── Built-in training sentences ─────────────────────────────────
TRAINING_DATA = [
    # --- Definitions (label 0) ---
    ("Machine learning is a subset of artificial intelligence.", "definition"),
    ("A neural network is a system of algorithms that recognizes patterns.", "definition"),
    ("Deep learning is defined as a class of machine learning using neural networks.", "definition"),
    ("An algorithm is a step-by-step procedure for solving a problem.", "definition"),
    ("Supervised learning is when a model learns from labeled training data.", "definition"),
    ("A transformer is a deep learning model based on self-attention mechanisms.", "definition"),
    ("Overfitting is when a model memorizes training data but fails on new data.", "definition"),
    ("A loss function measures how far predictions are from actual values.", "definition"),
    ("Gradient descent is an optimization algorithm used to minimize loss.", "definition"),
    ("Tokenization is the process of splitting text into smaller units called tokens.", "definition"),

    # --- Concepts (label 1) ---
    ("Neural networks consist of layers of interconnected nodes called neurons.", "concept"),
    ("Attention mechanisms allow models to focus on relevant parts of input.", "concept"),
    ("Backpropagation computes gradients by applying the chain rule.", "concept"),
    ("Embeddings represent words as dense vectors in a continuous space.", "concept"),
    ("Convolutional layers detect local patterns like edges in images.", "concept"),
    ("LSTM networks use gates to control the flow of information over time.", "concept"),
    ("Transfer learning reuses pretrained model weights for new tasks.", "concept"),
    ("The softmax function converts raw scores into probabilities.", "concept"),
    ("Regularization techniques like dropout prevent overfitting.", "concept"),
    ("Self-attention computes relationships between all tokens in a sequence.", "concept"),

    # --- Examples (label 2) ---
    ("For example, GPT-4 is a large language model used for text generation.", "example"),
    ("For instance, BERT is used for question answering and text classification.", "example"),
    ("A classic example of supervised learning is email spam detection.", "example"),
    ("Consider the case where a model predicts house prices from features.", "example"),
    ("For example, ResNet is a CNN architecture used for image recognition.", "example"),
    ("To illustrate, sentiment analysis classifies reviews as positive or negative.", "example"),
    ("As an example, Word2Vec learns word relationships from large text corpora.", "example"),
    ("For instance, a chatbot is an application of natural language processing.", "example"),
    ("Consider a recommendation system like Netflix that suggests movies.", "example"),
    ("For example, FAISS enables fast similarity search across millions of vectors.", "example"),

    # --- Important Points (label 3) ---
    ("It is crucial to normalize input data before training any neural network.", "important_point"),
    ("Always split your dataset into training, validation, and test sets.", "important_point"),
    ("The learning rate is one of the most critical hyperparameters to tune.", "important_point"),
    ("Data quality matters more than model complexity in most real-world tasks.", "important_point"),
    ("Vanishing gradients are a major challenge when training deep networks.", "important_point"),
    ("Batch normalization significantly improves training stability.", "important_point"),
    ("Without sufficient data, even the best model will underperform.", "important_point"),
    ("Evaluation on unseen test data is essential to measure true performance.", "important_point"),
    ("Feature engineering can often outperform complex model architectures.", "important_point"),
    ("Always validate your model using cross-validation to avoid overfitting.", "important_point"),
]


def prepare_dataset() -> tuple:
    """
    Converts raw training sentences into embeddings + labels.

    Steps:
    1. Extract sentences and labels from TRAINING_DATA
    2. Convert labels to integers using LABEL_MAP
    3. Generate sentence embeddings (384-dim vectors)
    4. Split into train/validation/test sets (70/15/15)

    Returns:
        tuple: (X_train, X_val, X_test, y_train, y_val, y_test)
               X = numpy arrays of embeddings
               y = numpy arrays of integer labels
    """

    print("[DATA] Preparing dataset...")

    # Unzip the list of (sentence, label) tuples
    sentences, label_names = zip(*TRAINING_DATA)

    # Convert label strings to integers
    # "definition" → 0,  "concept" → 1, etc.
    labels = np.array([LABEL_MAP[l] for l in label_names])

    print(f"[DATA] Total samples: {len(sentences)}")
    print(f"[DATA] Label distribution: { {k: list(labels).count(v) for k,v in LABEL_MAP.items()} }")

    # Generate embeddings for all sentences
    print("[DATA] Generating embeddings (this may take ~30 seconds)...")
    X = embed_sentences(list(sentences))  # Shape: (40, 384)
    y = labels                             # Shape: (40,)

    # First split: 70% train, 30% temp
    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.30, random_state=42, stratify=y
    )

    # Second split: 50% of temp = val, 50% = test (each is 15% of total)
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
    )

    print(f"[DATA] Train: {len(X_train)} | Val: {len(X_val)} | Test: {len(X_test)}")

    return X_train, X_val, X_test, y_train, y_val, y_test


def load_dataset_from_csv(csv_path: str) -> tuple:
    """
    (Optional) Load your own labeled dataset from a CSV file.

    Expected CSV format:
        sentence,label
        "Machine learning is AI","definition"
        "For example, BERT...","example"

    Args:
        csv_path (str): Path to your CSV file

    Returns:
        tuple: Same as prepare_dataset()
    """
    df = pd.read_csv(csv_path)
    sentences = df["sentence"].tolist()
    labels    = np.array([LABEL_MAP[l] for l in df["label"].tolist()])

    X = embed_sentences(sentences)
    y = labels

    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=0.30, random_state=42, stratify=y
    )
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
    )

    return X_train, X_val, X_test, y_train, y_val, y_test

# models/ann_model.py

"""
ANN — Artificial Neural Network Classifier
--------------------------------------------
Architecture:
  Input (384) → Dense(256) → ReLU → Dropout
              → Dense(128) → ReLU → Dropout
              → Dense(64)  → ReLU
              → Output(4)  → Softmax

Why this architecture?
- 384 input = sentence embedding size
- We gradually reduce dimensions (384→256→128→64→4)
  like funneling down to the answer
- ReLU adds non-linearity (lets model learn complex patterns)
- Dropout prevents overfitting (randomly turns off neurons during training)
- Softmax outputs 4 probabilities (one per class) that sum to 1.0
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np


class ANNClassifier(nn.Module):
    """
    Feedforward Neural Network for sentence classification.
    Inherits from nn.Module (PyTorch base class for all models).
    """

    def __init__(self, input_dim: int = 384, num_classes: int = 4):
        """
        Defines the layers of the network.

        Args:
            input_dim (int): Size of input embeddings (384 for MiniLM)
            num_classes (int): Number of output classes (4)
        """
        super(ANNClassifier, self).__init__()

        # nn.Sequential chains layers — input flows through them in order
        self.network = nn.Sequential(

            # Layer 1: 384 → 256
            nn.Linear(input_dim, 256),  # Fully connected layer
            nn.ReLU(),                   # Activation: max(0, x)
            nn.Dropout(0.3),             # Randomly zero 30% of neurons

            # Layer 2: 256 → 128
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),

            # Layer 3: 128 → 64
            nn.Linear(128, 64),
            nn.ReLU(),

            # Output Layer: 64 → 4 (one score per class)
            nn.Linear(64, num_classes)
            # No softmax here — CrossEntropyLoss applies it internally
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Forward pass — how data flows through the network.

        Args:
            x: Input tensor of shape (batch_size, 384)

        Returns:
            Tensor of shape (batch_size, 4) — raw class scores (logits)
        """
        return self.network(x)


def train_ann(X_train, y_train, X_val, y_val,
              epochs: int = 50, lr: float = 0.001) -> tuple:
    """
    Trains the ANN model.

    Args:
        X_train, y_train: Training embeddings and labels
        X_val,   y_val  : Validation embeddings and labels
        epochs (int)    : Number of training iterations
        lr (float)      : Learning rate (how big each weight update is)

    Returns:
        tuple: (trained_model, train_losses, val_losses)
    """

    # ── Convert numpy arrays to PyTorch tensors ──────────────────
    X_train_t = torch.FloatTensor(X_train)
    y_train_t = torch.LongTensor(y_train)
    X_val_t   = torch.FloatTensor(X_val)
    y_val_t   = torch.LongTensor(y_val)

    # ── DataLoader batches the data (processes 16 samples at a time) ──
    train_dataset = TensorDataset(X_train_t, y_train_t)
    train_loader  = DataLoader(train_dataset, batch_size=16, shuffle=True)

    # ── Initialize model, loss function, optimizer ────────────────
    model     = ANNClassifier()
    criterion = nn.CrossEntropyLoss()       # Good for multi-class classification
    optimizer = optim.Adam(model.parameters(), lr=lr)  # Adam: adaptive learning rate

    train_losses, val_losses = [], []

    print(f"\n[ANN] Training for {epochs} epochs...")

    for epoch in range(epochs):

        # ── Training phase ────────────────────────────────────────
        model.train()  # Enable dropout (training mode)
        epoch_loss = 0

        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()              # Clear old gradients
            outputs = model(X_batch)           # Forward pass
            loss    = criterion(outputs, y_batch)  # Calculate loss
            loss.backward()                    # Backpropagation
            optimizer.step()                   # Update weights
            epoch_loss += loss.item()

        avg_train_loss = epoch_loss / len(train_loader)
        train_losses.append(avg_train_loss)

        # ── Validation phase ──────────────────────────────────────
        model.eval()   # Disable dropout (evaluation mode)
        with torch.no_grad():  # Don't calculate gradients (saves memory)
            val_outputs = model(X_val_t)
            val_loss    = criterion(val_outputs, y_val_t).item()
            val_losses.append(val_loss)

        # Print progress every 10 epochs
        if (epoch + 1) % 10 == 0:
            print(f"  Epoch [{epoch+1}/{epochs}] "
                  f"Train Loss: {avg_train_loss:.4f} | "
                  f"Val Loss: {val_loss:.4f}")

    print("[ANN] Training complete! ✅")
    return model, train_losses, val_losses


def save_model(model, path: str = "models/saved/ann_model.pt"):
    """Saves trained model weights to disk."""
    import os
    os.makedirs("models/saved", exist_ok=True)
    torch.save(model.state_dict(), path)
    print(f"[ANN] Model saved to {path}")


def load_model(path: str = "models/saved/ann_model.pt") -> ANNClassifier:
    """Loads saved model weights from disk."""
    model = ANNClassifier()
    model.load_state_dict(torch.load(path))
    model.eval()
    print(f"[ANN] Model loaded from {path}")
    return model