# -*- coding: utf-8 -*-
"""EVALUATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17AOyvVYEKANJSV0-86wlWN0ov3Q8Xtta
"""

# models/evaluator.py

"""
Model Evaluator
----------------
Compares ANN, CNN, and LSTM using 4 key metrics:

┌─────────────────────────────────────────────────────────────────┐
│ METRIC     │ WHAT IT MEANS (Simple)                            │
├────────────┼────────────────────────────────────────────────────┤
│ Accuracy   │ % of ALL predictions that were correct            │
│ Precision  │ Of all "Definition" predictions, how many WERE?   │
│ Recall     │ Of all actual Definitions, how many did we FIND?  │
│ F1-Score   │ Balance between Precision & Recall (best overall) │
└────────────┴────────────────────────────────────────────────────┘

Use F1-Score as your primary metric — it handles class imbalance.
"""

import torch
import numpy as np
from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score, classification_report
)
from models.data_prep import ID_TO_LABEL


def get_predictions(model, X_test: np.ndarray) -> np.ndarray:
    """
    Runs model on test data and returns predicted class indices.

    Args:
        model: Trained PyTorch model (ANN, CNN, or LSTM)
        X_test: Test embeddings array

    Returns:
        np.ndarray: Predicted class indices
    """
    model.eval()
    with torch.no_grad():
        X_tensor = torch.FloatTensor(X_test)
        logits   = model(X_tensor)               # Raw scores per class
        probs    = torch.softmax(logits, dim=1)  # Convert to probabilities
        preds    = torch.argmax(probs, dim=1)    # Pick highest probability
    return preds.numpy()


def evaluate_model(model, X_test: np.ndarray,
                   y_test: np.ndarray, model_name: str) -> dict:
    """
    Evaluates a single model and prints a full report.

    Args:
        model      : Trained model
        X_test     : Test embeddings
        y_test     : True labels
        model_name : Name for display ("ANN", "CNN", "LSTM")

    Returns:
        dict: {"accuracy", "precision", "recall", "f1"}
    """

    preds = get_predictions(model, X_test)

    # Calculate metrics
    accuracy  = accuracy_score(y_test, preds)
    precision = precision_score(y_test, preds, average="weighted", zero_division=0)
    recall    = recall_score(y_test, preds, average="weighted", zero_division=0)
    f1        = f1_score(y_test, preds, average="weighted", zero_division=0)

    print(f"\n{'='*50}")
    print(f"  {model_name} Evaluation Results")
    print(f"{'='*50}")
    print(f"  Accuracy  : {accuracy:.4f}  ({accuracy*100:.1f}%)")
    print(f"  Precision : {precision:.4f}")
    print(f"  Recall    : {recall:.4f}")
    print(f"  F1-Score  : {f1:.4f}  ← Primary metric")
    print(f"{'='*50}")

    # Detailed per-class report
    label_names = [ID_TO_LABEL[i] for i in range(4)]
    print(f"\nPer-class breakdown:\n")
    print(classification_report(y_test, preds, target_names=label_names, zero_division=0))

    return {"accuracy": accuracy, "precision": precision,
            "recall": recall, "f1": f1}


def compare_models(results: dict):
    """
    Prints a side-by-side comparison table of all 3 models.

    Args:
        results (dict): {"ANN": {...metrics}, "CNN": {...}, "LSTM": {...}}
    """

    print("\n" + "="*65)
    print("          MODEL COMPARISON SUMMARY")
    print("="*65)
    print(f"{'Model':<10} {'Accuracy':>10} {'Precision':>10} {'Recall':>10} {'F1-Score':>10}")
    print("-"*65)

    best_model = max(results, key=lambda m: results[m]["f1"])

    for model_name, metrics in results.items():
        marker = " ← BEST" if model_name == best_model else ""
        print(f"{model_name:<10} "
              f"{metrics['accuracy']:>10.4f} "
              f"{metrics['precision']:>10.4f} "
              f"{metrics['recall']:>10.4f} "
              f"{metrics['f1']:>10.4f}{marker}")

    print("="*65)
    print(f"\n🏆 Best Model: {best_model} (by F1-Score)")
    print("\n📌 How to read these results:")
    print("  • Accuracy  — Overall % correct (can be misleading with imbalanced data)")
    print("  • Precision — When model says 'X', how often is it right?")
    print("  • Recall    — Out of all actual 'X', how many did it catch?")
    print("  • F1-Score  — Harmonic mean of Precision & Recall (best single metric)")