# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f3WUrV73NKwV6AHJRV41tLyCFREVLg4i
"""

# models/lstm_model.py

"""
LSTM — Long Short-Term Memory for Text Classification
------------------------------------------------------
Unlike ANN/CNN which treat input as a flat vector,
LSTM processes it as a sequence — step by step.

Why LSTM for text?
  "The food was not good" vs "The food was good"
  → The word "not" early in the sentence changes the meaning
  → LSTM remembers "not" when it reaches "good" ✅
  → ANN treats both as similar vectors ❌

Architecture:
  Input (384) → Reshape to sequence (24 steps × 16 features)
              → LSTM(hidden=128, layers=2)
              → Last hidden state
              → Dense(64) → Output(4)
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset


class LSTMClassifier(nn.Module):

    def __init__(self, input_size: int = 16, hidden_size: int = 128,
                 num_layers: int = 2, num_classes: int = 4,
                 seq_len: int = 24):
        """
        Args:
            input_size  : Features per time step (384/24 = 16)
            hidden_size : LSTM hidden state size
            num_layers  : Stacked LSTM layers (deeper = better, but slower)
            num_classes : Output classes (4)
            seq_len     : How we split the 384-dim vector into steps
        """
        super(LSTMClassifier, self).__init__()

        self.seq_len    = seq_len      # 24 steps
        self.input_size = input_size   # 16 features per step

        # LSTM layer
        # batch_first=True means input shape is (batch, seq, features)
        self.lstm = nn.LSTM(
            input_size  = input_size,
            hidden_size = hidden_size,
            num_layers  = num_layers,
            batch_first = True,
            dropout     = 0.3         # Dropout between LSTM layers
        )

        # Final classifier
        self.classifier = nn.Sequential(
            nn.Linear(hidden_size, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, num_classes)
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x shape: (batch_size, 384)

        We reshape 384-dim vector into sequence:
        (batch, 384) → (batch, 24, 16)
        → 24 time steps, each with 16 features
        """
        # Reshape flat embedding into sequence
        x = x.view(x.size(0), self.seq_len, self.input_size)

        # LSTM forward pass
        # lstm_out: all hidden states (batch, seq, hidden)
        # (h_n, c_n): final hidden & cell states
        lstm_out, (h_n, c_n) = self.lstm(x)

        # Use only the LAST time step's output for classification
        last_hidden = lstm_out[:, -1, :]  # Shape: (batch, hidden_size)

        # Pass through classifier
        output = self.classifier(last_hidden)
        return output


def train_lstm(X_train, y_train, X_val, y_val,
               epochs: int = 50, lr: float = 0.001) -> tuple:
    """Trains the LSTM model."""

    X_train_t = torch.FloatTensor(X_train)
    y_train_t = torch.LongTensor(y_train)
    X_val_t   = torch.FloatTensor(X_val)
    y_val_t   = torch.LongTensor(y_val)

    train_loader = DataLoader(
        TensorDataset(X_train_t, y_train_t),
        batch_size=16, shuffle=True
    )

    model     = LSTMClassifier()
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    train_losses, val_losses = [], []

    print(f"\n[LSTM] Training for {epochs} epochs...")

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0

        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            outputs = model(X_batch)
            loss    = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()

        avg_train_loss = epoch_loss / len(train_loader)
        train_losses.append(avg_train_loss)

        model.eval()
        with torch.no_grad():
            val_loss = criterion(model(X_val_t), y_val_t).item()
            val_losses.append(val_loss)

        if (epoch + 1) % 10 == 0:
            print(f"  Epoch [{epoch+1}/{epochs}] "
                  f"Train Loss: {avg_train_loss:.4f} | Val Loss: {val_loss:.4f}")

    print("[LSTM] Training complete! ✅")
    return model, train_losses, val_losses