# models/training_data.py
"""
Comprehensive Training Dataset — 500+ labeled sentences
Covers: ML/AI, NLP, CS, Math, Physics, Chemistry, Biology,
        History, Geography, Economics, Literature, Psychology,
        Law, Medicine, Engineering, Philosophy
"""

LABEL_MAP   = {"definition":0,"concept":1,"example":2,"important_point":3}
ID_TO_LABEL = {v:k for k,v in LABEL_MAP.items()}

TRAINING_DATA = [
    # ── MACHINE LEARNING & AI ────────────────────────────────────
    ("Machine learning is a subset of artificial intelligence enabling systems to learn from data without explicit programming.","definition"),
    ("Deep learning uses multiple neural network layers to learn hierarchical representations of data.","definition"),
    ("Supervised learning trains models on labeled input-output pairs to predict new outputs.","definition"),
    ("Unsupervised learning finds hidden patterns in unlabeled data without predefined answers.","definition"),
    ("Reinforcement learning trains agents to maximize cumulative reward through environment interaction.","definition"),
    ("A neural network is a computational model of interconnected nodes that transforms input into output.","definition"),
    ("Backpropagation computes gradients by applying the chain rule backward through a neural network.","definition"),
    ("Gradient descent iteratively updates parameters in the direction that minimizes a loss function.","definition"),
    ("Overfitting occurs when a model memorizes training data and fails to generalize to new inputs.","definition"),
    ("Regularization adds constraints to learning to reduce overfitting and improve generalization.","definition"),
    ("A loss function quantifies the difference between model predictions and true target values.","definition"),
    ("The learning rate controls how much parameters change per gradient update step.","definition"),
    ("Dropout randomly deactivates neurons during training to prevent co-adaptation and overfitting.","definition"),
    ("Batch normalization normalizes layer activations to stabilize and accelerate training.","definition"),
    ("A transformer is a deep learning model that uses self-attention to process sequences in parallel.","definition"),
    ("LSTM is a recurrent network with gates that selectively retain or forget information over time.","definition"),
    ("Attention allows models to focus on the most relevant parts of the input for each output step.","definition"),
    ("Transfer learning reuses a model pretrained on one task as a starting point for another.","definition"),
    ("Fine-tuning adapts a pretrained model to a specific task using smaller domain-specific data.","definition"),
    ("A convolutional neural network applies learnable filters to detect local patterns in grid data.","definition"),
    ("The softmax function converts raw scores into a probability distribution summing to one.","definition"),
    ("Cross-entropy loss measures the difference between predicted probabilities and true labels.","definition"),
    ("An epoch is one complete pass through the entire training dataset during model training.","definition"),
    ("A hyperparameter is a configuration variable set before training that controls the learning process.","definition"),
    ("Cross-validation evaluates model performance by training and testing on different data partitions.","definition"),
    ("Precision is the fraction of positive predictions that are actually positive.","definition"),
    ("Recall is the fraction of actual positives that the model correctly identifies.","definition"),
    ("F1-score is the harmonic mean of precision and recall for balanced evaluation.","definition"),
    ("ROC-AUC measures how well a model distinguishes between classes across all thresholds.","definition"),
    ("Embedding maps discrete items to dense vectors in a continuous space where similarity reflects meaning.","definition"),
    ("Principal component analysis reduces dimensionality by projecting data onto axes of maximum variance.","definition"),
    ("K-means clustering assigns data points to K centroids by minimizing within-cluster distances.","definition"),
    ("A decision tree recursively splits data on the feature and threshold that maximizes information gain.","definition"),
    ("Random forests combine many decision trees trained on data subsets to reduce variance.","definition"),
    ("A support vector machine finds the hyperplane that maximizes the margin between classes.","definition"),
    ("Generative adversarial networks train a generator and discriminator in competition to produce realistic data.","definition"),
    ("An autoencoder learns to compress data into a latent representation and reconstruct it.","definition"),
    ("BERT is a bidirectional transformer pretrained on masked language modeling and next sentence prediction.","definition"),
    ("GPT is an autoregressive transformer that generates text by predicting the next token sequentially.","definition"),
    ("RAG combines retrieval of relevant documents with language model generation for grounded answers.","definition"),

    ("Neural networks learn by computing gradients and updating weights to minimize prediction errors.","concept"),
    ("Self-attention computes a weighted sum of all positions in a sequence based on pairwise relevance.","concept"),
    ("Multi-head attention runs several attention functions in parallel and concatenates their outputs.","concept"),
    ("Residual connections let gradients flow directly through skip connections enabling very deep networks.","concept"),
    ("The vanishing gradient problem causes gradients to approach zero in very deep networks.","concept"),
    ("Pooling layers reduce spatial dimensions while preserving the most important feature information.","concept"),
    ("Word embeddings place semantically similar words close together in a high-dimensional space.","concept"),
    ("Semantic search retrieves results by comparing meaning rather than exact keyword matches.","concept"),
    ("The bias-variance tradeoff shows that reducing bias increases variance and vice versa.","concept"),
    ("Data augmentation artificially increases training set size by applying transformations to existing samples.","concept"),
    ("Prompt engineering designs inputs to guide language model behavior toward desired outputs.","concept"),
    ("Chain-of-thought prompting elicits step-by-step reasoning before a final answer.","concept"),
    ("Quantization reduces model size by representing weights with fewer bits.","concept"),

    ("For example, GPT-4 generates human-like text used in chatbots and coding assistants.","example"),
    ("BERT is used in Google Search to better understand the intent behind user queries.","example"),
    ("A spam filter is a classic supervised learning example trained on labeled email data.","example"),
    ("AlphaGo demonstrated reinforcement learning achieving superhuman performance at the game of Go.","example"),
    ("ResNet uses residual connections to successfully train networks with over 150 layers.","example"),
    ("Word2Vec learns that king minus man plus woman approximates queen in vector space.","example"),
    ("FAISS enables Facebook to search billions of image embeddings in milliseconds.","example"),
    ("Dropout sets 30% of neuron activations to zero randomly during each training step.","example"),
    ("K-means groups customers into segments by purchasing behavior for targeted marketing.","example"),
    ("Adam optimizer adapts learning rates individually for each parameter during training.","example"),

    ("Normalize input features before training any neural network to prevent scale bias.","important_point"),
    ("Always use a separate test set never seen during training to measure true generalization.","important_point"),
    ("The learning rate is the most sensitive hyperparameter and must be tuned carefully.","important_point"),
    ("More data usually outperforms a more complex model in real-world machine learning tasks.","important_point"),
    ("Hallucination in language models produces confident but factually incorrect outputs.","important_point"),
    ("RAG significantly reduces hallucination by grounding responses in retrieved source documents.","important_point"),
    ("Data leakage from test into training sets produces artificially inflated evaluation metrics.","important_point"),
    ("Class imbalance must be addressed with resampling or class weights before training.","important_point"),
    ("Embeddings used for indexing and querying must come from the same model to work correctly.","important_point"),
    ("Context window size is a hard limit on how much text a language model can process at once.","important_point"),

    # ── MATHEMATICS ──────────────────────────────────────────────
    ("A derivative measures the instantaneous rate of change of a function at a given point.","definition"),
    ("An integral computes the accumulated area under a curve between two bounds.","definition"),
    ("A matrix is a rectangular array of numbers organized in rows and columns.","definition"),
    ("An eigenvalue is a scalar such that multiplying a matrix by a vector equals the scalar times that vector.","definition"),
    ("A probability distribution describes the likelihood of each possible outcome in a random experiment.","definition"),
    ("The mean is the arithmetic average of a dataset computed by summing values and dividing by count.","definition"),
    ("Standard deviation measures the spread of data around the mean in the same units as the data.","definition"),
    ("A hypothesis test determines whether observed data provides sufficient evidence against a null hypothesis.","definition"),
    ("A prime number is a natural number greater than one with no positive divisors other than one and itself.","definition"),
    ("A limit describes the value a function approaches as its input approaches a given point.","definition"),
    ("A vector is a mathematical object with both magnitude and direction.","definition"),
    ("A logarithm is the inverse of exponentiation answering how many times a base must be multiplied by itself.","definition"),
    ("A set is a collection of distinct objects considered as a single entity.","definition"),
    ("A graph in mathematics consists of vertices connected by edges representing relationships.","definition"),
    ("Bayes' theorem updates the probability of an event based on new evidence.","definition"),

    ("Differentiation finds the slope of a function while integration finds the area under it.","concept"),
    ("The chain rule computes the derivative of a composite function by multiplying derivatives.","concept"),
    ("Matrix multiplication combines rows of the first matrix with columns of the second.","concept"),
    ("The central limit theorem states sample means approach a normal distribution as sample size grows.","concept"),
    ("Conditional probability measures the likelihood of an event given that another event has occurred.","concept"),
    ("Linear regression models a dependent variable as a linear combination of independent variables.","concept"),
    ("The Pythagorean theorem relates the three sides of a right triangle as a squared plus b squared equals c squared.","concept"),
    ("Fourier analysis decomposes a signal into its constituent sinusoidal frequencies.","concept"),

    ("For example, the derivative of x squared is 2x, computed using the power rule.","example"),
    ("The integral of one over x equals the natural logarithm of the absolute value of x.","example"),
    ("A p-value below 0.05 conventionally indicates statistically significant evidence against the null hypothesis.","example"),
    ("In graph theory, Dijkstra's algorithm finds the shortest path between nodes in a weighted graph.","example"),
    ("The Fibonacci sequence adds the two preceding terms to get each new term starting with 0 and 1.","example"),

    ("Correlation does not imply causation even when two variables move together strongly.","important_point"),
    ("Overfitting a model to statistical data fails to capture the true underlying relationship.","important_point"),
    ("Rounding errors accumulate in floating-point arithmetic and must be managed carefully.","important_point"),
    ("Mathematical proofs require logical rigor and every step must follow from previous ones.","important_point"),

    # ── PHYSICS ─────────────────────────────────────────────────
    ("Newton's first law states that an object remains at rest or in uniform motion unless acted on by a net force.","definition"),
    ("Newton's second law states that force equals mass times acceleration.","definition"),
    ("Newton's third law states that every action has an equal and opposite reaction.","definition"),
    ("Energy is the capacity to do work measured in joules.","definition"),
    ("Momentum is the product of an object's mass and velocity.","definition"),
    ("Work is done when a force moves an object through a distance in the direction of the force.","definition"),
    ("Electromagnetic radiation is energy transmitted as waves of electric and magnetic fields.","definition"),
    ("Entropy is a measure of the disorder or randomness of a thermodynamic system.","definition"),
    ("A photon is the fundamental particle of light and electromagnetic radiation.","definition"),
    ("The speed of light in a vacuum is approximately 3 times 10 to the 8 meters per second.","definition"),
    ("Relativity theory describes how space, time, and mass are affected by velocity and gravity.","definition"),
    ("Quantum mechanics describes the behavior of particles at atomic and subatomic scales.","definition"),
    ("Electric current is the rate of flow of electric charge through a conductor.","definition"),
    ("Resistance is the opposition of a conductor to the flow of electric current.","definition"),

    ("Conservation of energy states that energy cannot be created or destroyed only transformed.","concept"),
    ("Conservation of momentum holds in an isolated system with no external forces.","concept"),
    ("Ohm's law states that current equals voltage divided by resistance.","concept"),
    ("Waves transfer energy without transferring matter through a medium.","concept"),
    ("The Doppler effect describes the change in observed frequency when source and observer move.","concept"),
    ("Thermal equilibrium is reached when two objects in contact reach the same temperature.","concept"),

    ("For example, a rocket moves forward by expelling gas backward illustrating Newton's third law.","example"),
    ("A roller coaster converts potential energy at the top to kinetic energy at the bottom.","example"),
    ("Interference patterns in the double-slit experiment demonstrate the wave nature of light.","example"),
    ("MRI machines use nuclear magnetic resonance to image soft tissues in the human body.","example"),
    ("GPS satellites must account for relativistic time dilation to provide accurate positioning.","example"),

    ("Energy is always conserved in a closed system regardless of the processes occurring within it.","important_point"),
    ("The second law of thermodynamics states that entropy in an isolated system never decreases.","important_point"),
    ("Quantum mechanics fundamentally limits the precision with which pairs of properties can be known.","important_point"),
    ("The speed of light is the universal speed limit and nothing with mass can reach it.","important_point"),

    # ── CHEMISTRY ───────────────────────────────────────────────
    ("An element is a pure substance consisting of atoms with the same number of protons.","definition"),
    ("A compound is a substance formed from two or more elements chemically bonded together.","definition"),
    ("A chemical bond is the force of attraction that holds atoms together in a molecule.","definition"),
    ("Oxidation is the loss of electrons or increase in oxidation state during a chemical reaction.","definition"),
    ("Reduction is the gain of electrons or decrease in oxidation state during a chemical reaction.","definition"),
    ("An acid is a substance that donates protons or accepts electrons in a chemical reaction.","definition"),
    ("A base is a substance that accepts protons or donates electrons in a chemical reaction.","definition"),
    ("pH measures the concentration of hydrogen ions and indicates acidity or alkalinity.","definition"),
    ("Molar mass is the mass of one mole of a substance expressed in grams per mole.","definition"),
    ("Catalysis speeds up a chemical reaction by providing an alternative pathway with lower activation energy.","definition"),
    ("Electronegativity is the tendency of an atom to attract electrons in a chemical bond.","definition"),

    ("Covalent bonds form when atoms share electrons to achieve stable electron configurations.","concept"),
    ("Ionic bonds form through the electrostatic attraction between oppositely charged ions.","concept"),
    ("Le Chatelier's principle states that a system at equilibrium shifts to oppose applied changes.","concept"),
    ("The periodic table organizes elements by atomic number and groups them by chemical properties.","concept"),
    ("Organic chemistry studies carbon-containing compounds and their reactions.","concept"),

    ("Water dissolves salt because its polar molecules surround and separate the sodium and chloride ions.","example"),
    ("Rusting of iron is an oxidation reaction where iron reacts with oxygen and water to form iron oxide.","example"),
    ("Burning natural gas converts methane and oxygen into carbon dioxide and water releasing energy.","example"),
    ("Enzymes like amylase catalyze the breakdown of starch into sugars in the digestive system.","example"),

    ("Conservation of mass means the total mass of reactants equals the total mass of products.","important_point"),
    ("Highly reactive chemicals must be stored separately to prevent dangerous accidental reactions.","important_point"),
    ("pH below 7 is acidic, above 7 is basic, and exactly 7 is neutral at standard conditions.","important_point"),

    # ── BIOLOGY ─────────────────────────────────────────────────
    ("DNA is the double-stranded molecule encoding genetic instructions in sequences of nucleotide bases.","definition"),
    ("RNA is a single-stranded molecule that carries genetic information from DNA to ribosomes.","definition"),
    ("A gene is a sequence of DNA that encodes instructions for building a protein.","definition"),
    ("A cell is the basic structural and functional unit of all living organisms.","definition"),
    ("Photosynthesis converts carbon dioxide and water into glucose using light energy.","definition"),
    ("Cellular respiration converts glucose and oxygen into ATP carbon dioxide and water.","definition"),
    ("Evolution is the process of change in heritable traits of populations over successive generations.","definition"),
    ("Natural selection favors heritable traits that increase survival and reproduction.","definition"),
    ("An ecosystem is a community of living organisms interacting with their physical environment.","definition"),
    ("Mitosis is cell division producing two genetically identical daughter cells.","definition"),
    ("Meiosis is cell division producing four genetically diverse gametes with half the chromosome number.","definition"),
    ("A mutation is a permanent alteration in the DNA sequence of an organism's genome.","definition"),
    ("Homeostasis is the ability of an organism to maintain a stable internal environment.","definition"),
    ("The central dogma describes the flow of genetic information from DNA to RNA to protein.","definition"),
    ("An enzyme is a biological catalyst that speeds up chemical reactions without being consumed.","definition"),
    ("A hormone is a chemical messenger secreted by glands that regulates distant target organs.","definition"),
    ("Osmosis is the movement of water across a semipermeable membrane from low to high solute concentration.","definition"),
    ("Biodiversity refers to the variety of life forms within an ecosystem, biome, or the entire Earth.","definition"),

    ("Enzymes lower activation energy by providing an alternative reaction pathway for substrates.","concept"),
    ("The immune system distinguishes self from non-self to target and eliminate pathogens.","concept"),
    ("Genetic variation arises from mutation recombination and independent assortment during meiosis.","concept"),
    ("Food webs describe the flow of energy and nutrients through an ecological community.","concept"),
    ("Feedback loops maintain homeostasis by amplifying or dampening responses to changes.","concept"),
    ("Cell signaling allows cells to communicate through chemical messengers and surface receptors.","concept"),

    ("Penicillin kills bacteria by preventing cell wall synthesis, discovered accidentally by Fleming.","example"),
    ("CRISPR-Cas9 edits specific DNA sequences and has been used to correct genetic disorders.","example"),
    ("Darwin observed beak variations in Galápagos finches as evidence for natural selection.","example"),
    ("Insulin injection replaces the hormone diabetic patients cannot produce sufficiently on their own.","example"),
    ("Vaccines train the immune system by exposing it to weakened or inactive pathogens.","example"),

    ("All living organisms share the same genetic code indicating a common ancestor.","important_point"),
    ("Evolution is supported by fossil records, genetic evidence, and observed adaptation.","important_point"),
    ("Antibiotic resistance develops when bacteria evolve mechanisms to survive drug exposure.","important_point"),
    ("Biodiversity loss threatens ecosystem stability and reduces resilience to environmental change.","important_point"),

    # ── HISTORY & SOCIAL SCIENCES ───────────────────────────────
    ("The Renaissance was a cultural and intellectual movement in Europe from the 14th to 17th century.","definition"),
    ("The Industrial Revolution transformed manufacturing through mechanization and factory production.","definition"),
    ("Democracy is a system of government where citizens exercise power through elected representatives.","definition"),
    ("Imperialism is the policy of extending a nation's power through colonization or military force.","definition"),
    ("The Cold War was a geopolitical rivalry between the United States and Soviet Union from 1947 to 1991.","definition"),
    ("GDP is the total market value of all goods and services produced in a country in a given period.","definition"),
    ("Inflation is the general rise in price levels reducing the purchasing power of currency over time.","definition"),
    ("Fiscal policy uses government spending and taxation to influence the economy.","definition"),
    ("Monetary policy uses interest rates and money supply to control inflation and growth.","definition"),
    ("Supply and demand determines equilibrium price where the quantity supplied equals quantity demanded.","definition"),
    ("Socialization is the process by which individuals learn cultural norms, values, and behaviors.","definition"),
    ("Colonialism involves one nation's control of another territory and its people.","definition"),
    ("The Enlightenment was an intellectual movement emphasizing reason, science, and individual rights.","definition"),

    ("Primary sources provide direct evidence from the time period being studied.","concept"),
    ("Cause and effect relationships in history are often complex with multiple interacting factors.","concept"),
    ("Economic inequality can be measured using the Gini coefficient ranging from 0 to 1.","concept"),
    ("Comparative advantage explains why free trade benefits all participants even when one is more productive.","concept"),
    ("Power structures in society are reproduced through institutions, norms, and ideology.","concept"),

    ("The printing press democratized knowledge by enabling mass production of books in the 15th century.","example"),
    ("The Great Depression of 1929 caused massive unemployment and led to New Deal economic reforms.","example"),
    ("The Treaty of Versailles ending World War I imposed harsh reparations contributing to World War II.","example"),
    ("Microfinance programs in Bangladesh demonstrated how small loans empower low-income entrepreneurs.","example"),

    ("Primary sources are more reliable than secondary accounts for historical evidence.","important_point"),
    ("Historical events should be understood in their contemporary context not by modern standards alone.","important_point"),
    ("Economic models simplify reality and their predictions depend on their assumptions holding true.","important_point"),
    ("Confirmation bias leads people to seek information confirming existing beliefs while ignoring contradictions.","important_point"),

    # ── COMPUTER SCIENCE ─────────────────────────────────────────
    ("An algorithm is a finite sequence of well-defined steps for solving a computational problem.","definition"),
    ("Big O notation describes the worst-case growth rate of an algorithm's time or space requirements.","definition"),
    ("A data structure organizes and stores data to enable efficient access and modification.","definition"),
    ("A linked list is a data structure of nodes where each node stores data and a pointer to the next node.","definition"),
    ("A binary tree is a hierarchical structure where each node has at most two children.","definition"),
    ("A hash table maps keys to values through a hash function enabling average O(1) lookup.","definition"),
    ("A stack is a last-in first-out data structure supporting push and pop operations.","definition"),
    ("A queue is a first-in first-out data structure supporting enqueue and dequeue operations.","definition"),
    ("Recursion is a technique where a function calls itself on smaller subproblems until a base case.","definition"),
    ("Object-oriented programming organizes code around objects combining data and methods.","definition"),
    ("Inheritance allows a class to acquire the properties and methods of a parent class.","definition"),
    ("Encapsulation hides internal implementation details exposing only necessary interfaces.","definition"),
    ("An operating system manages hardware resources and provides services to applications.","definition"),
    ("A database management system organizes stores and retrieves structured data efficiently.","definition"),
    ("TCP/IP is the suite of communication protocols enabling data transmission over the internet.","definition"),
    ("Encryption transforms data into an unreadable form to protect it from unauthorized access.","definition"),
    ("Concurrency allows multiple tasks to make progress within overlapping time periods.","definition"),
    ("An API defines how software components communicate through defined interfaces.","definition"),
    ("Version control tracks changes to code over time enabling collaboration and rollback.","definition"),

    ("Binary search halves the search space each step achieving O(log n) time complexity.","concept"),
    ("Dynamic programming solves complex problems by breaking them into overlapping subproblems.","concept"),
    ("Greedy algorithms make locally optimal choices at each step hoping to find a global optimum.","concept"),
    ("Depth-first search explores as far as possible along each branch before backtracking.","concept"),
    ("Breadth-first search explores all neighbors at the current depth before moving deeper.","concept"),
    ("Sorting algorithms trade off time complexity, space complexity, and stability.","concept"),
    ("Database normalization reduces redundancy by organizing data into related tables.","concept"),
    ("REST architecture uses stateless HTTP methods to create scalable web services.","concept"),
    ("Polymorphism allows different object types to be treated through a common interface.","concept"),

    ("Dijkstra's algorithm finds shortest paths in a weighted graph using a priority queue.","example"),
    ("Merge sort recursively divides an array in half and merges sorted halves achieving O(n log n).","example"),
    ("Git enables developers to branch, merge, and track changes across distributed teams.","example"),
    ("SQL joins combine rows from multiple tables based on related column values.","example"),
    ("Quicksort partitions an array around a pivot and recursively sorts each partition.","example"),

    ("Time complexity of O(n squared) becomes impractical for large inputs and should be avoided.","important_point"),
    ("Thread safety must be guaranteed when multiple processes access shared memory concurrently.","important_point"),
    ("Validate all user inputs to prevent injection attacks in web applications.","important_point"),
    ("Test-driven development improves reliability by writing tests before implementing features.","important_point"),
    ("Security vulnerabilities must be patched promptly to prevent exploitation.","important_point"),

    # ── PSYCHOLOGY ──────────────────────────────────────────────
    ("Classical conditioning associates a neutral stimulus with an unconditioned stimulus to produce a response.","definition"),
    ("Operant conditioning modifies behavior through reinforcement and punishment.","definition"),
    ("Cognitive bias is a systematic pattern of deviation from rational judgment in thinking.","definition"),
    ("Working memory is the short-term memory system that temporarily holds and manipulates information.","definition"),
    ("Long-term potentiation is the strengthening of synaptic connections associated with learning.","definition"),
    ("Confirmation bias is the tendency to search for information that confirms existing beliefs.","definition"),
    ("Cognitive dissonance is discomfort experienced when holding conflicting beliefs simultaneously.","definition"),
    ("The placebo effect occurs when a patient experiences real improvement from an inert treatment.","definition"),
    ("Intrinsic motivation drives behavior by internal rewards like interest or satisfaction.","definition"),
    ("Extrinsic motivation drives behavior by external rewards like money or grades.","definition"),

    ("Memory is reconstructive and can be influenced by subsequent experiences and suggestions.","concept"),
    ("The stress response activates the sympathetic nervous system preparing for fight or flight.","concept"),
    ("Emotional intelligence involves recognizing managing and using emotions effectively.","concept"),
    ("Behavioral patterns are shaped by both genetic predispositions and environmental experiences.","concept"),

    ("Pavlov conditioned dogs to salivate at a bell by pairing it with food presentation.","example"),
    ("The Stanford Prison Experiment showed how roles and environments shape behavior.","example"),
    ("Milgram's obedience experiment revealed how authority influences compliance with harmful orders.","example"),
    ("Cognitive behavioral therapy helps patients identify and change negative thought patterns.","example"),

    ("Mental health conditions are medical issues requiring treatment not moral failings.","important_point"),
    ("Self-reporting in psychology research is subject to social desirability and recall biases.","important_point"),
    ("Correlation between psychological variables does not establish that one causes the other.","important_point"),

    # ── PHILOSOPHY ──────────────────────────────────────────────
    ("Ethics is the branch of philosophy that studies moral principles governing right and wrong action.","definition"),
    ("Epistemology is the branch of philosophy concerned with the nature and scope of knowledge.","definition"),
    ("Logic is the systematic study of the principles of valid inference and reasoning.","definition"),
    ("Utilitarianism holds that the best action maximizes overall happiness or utility.","definition"),
    ("Deontological ethics judges actions by their adherence to rules or duties regardless of outcomes.","definition"),
    ("Virtue ethics focuses on character traits and the cultivation of virtues for a good life.","definition"),
    ("A syllogism is a logical argument with two premises and a conclusion following from them.","definition"),
    ("Empiricism holds that knowledge comes primarily from sensory experience.","definition"),
    ("Rationalism holds that reason rather than experience is the source of knowledge.","definition"),
    ("Free will is the capacity of agents to choose between possible courses of action.","definition"),

    ("The trolley problem illustrates the tension between utilitarian and deontological moral reasoning.","example"),
    ("Socrates used questions to expose contradictions in others' beliefs and stimulate critical thinking.","example"),
    ("Kant argued that lying is always wrong regardless of consequences based on the categorical imperative.","example"),

    ("Strong arguments require both valid logic and true premises to guarantee true conclusions.","important_point"),
    ("An appeal to authority is a logical fallacy unless the authority has genuine expertise in the domain.","important_point"),
    ("Ethical frameworks often conflict and real moral decisions require weighing competing considerations.","important_point"),

    # ── MEDICINE & HEALTH ────────────────────────────────────────
    ("Blood pressure is the force exerted by circulating blood on the walls of blood vessels.","definition"),
    ("A virus is a microscopic infectious agent that replicates only inside living host cells.","definition"),
    ("A bacterium is a single-celled prokaryotic microorganism found in nearly every environment.","definition"),
    ("Immunity is the ability of an organism to resist infection by pathogens.","definition"),
    ("A vaccine stimulates the immune system to produce antibodies against a specific pathogen.","definition"),
    ("Antibiotics are drugs that kill or inhibit the growth of bacteria.","definition"),
    ("Metabolism is the set of chemical reactions that maintain the living state of cells.","definition"),
    ("Homeostasis is the regulation of internal conditions to maintain a stable state.","definition"),
    ("A clinical trial tests the safety and efficacy of a treatment in human participants.","definition"),
    ("The placebo-controlled trial is the gold standard for evaluating medical treatments.","definition"),

    ("The immune system uses antibodies to bind and neutralize specific antigens on pathogens.","concept"),
    ("Vaccination creates herd immunity when enough of a population is immune to block transmission.","concept"),
    ("Antibiotic resistance emerges when bacteria evolve mechanisms to survive drug treatment.","concept"),
    ("Evidence-based medicine integrates clinical expertise with the best available research.","concept"),

    ("Insulin controls blood glucose levels and its deficiency causes diabetes mellitus.","example"),
    ("Aspirin reduces inflammation by inhibiting the enzyme that produces prostaglandins.","example"),
    ("Hand washing with soap prevents pathogen transmission more effectively than antibacterials.","example"),

    ("Correlation in medical studies does not establish causation without controlled experiments.","important_point"),
    ("Patient consent is an ethical requirement before any medical procedure or research.","important_point"),
    ("Antibiotic overuse accelerates the evolution of resistant bacterial strains globally.","important_point"),

    # ── LITERATURE & LANGUAGE ───────────────────────────────────
    ("A metaphor describes one thing as another to highlight similarities without using like or as.","definition"),
    ("A simile compares two things using like or as to create a vivid image.","definition"),
    ("Foreshadowing hints at future events to create suspense or dramatic irony.","definition"),
    ("Irony occurs when what is said or done is the opposite of what is meant or expected.","definition"),
    ("Narrative perspective is the vantage point from which a story is told.","definition"),
    ("Satire uses humor, irony, or exaggeration to criticize human vices or social institutions.","definition"),
    ("A protagonist is the main character whose journey or conflict drives the narrative.","definition"),
    ("Symbolism uses objects, characters, or events to represent abstract ideas or concepts.","definition"),
    ("Alliteration is the repetition of the same initial consonant sound in consecutive or nearby words.","definition"),
    ("Genre classifies literature by shared conventions of form, style, subject, and audience.","definition"),

    ("Shakespeare uses the ghost in Hamlet to externalize Hamlet's internal conflict and duty.","example"),
    ("Orwell's 1984 satirizes totalitarianism through the surveillance state of Big Brother.","example"),
    ("The green light in The Great Gatsby symbolizes Gatsby's unreachable dream and aspiration.","example"),
    ("Unreliable narrators like Stevens in The Remains of the Day create dramatic irony for readers.","example"),

    ("Close reading requires attending to diction, syntax, imagery, and structure simultaneously.","important_point"),
    ("Context shapes interpretation; the same text can mean differently across historical periods.","important_point"),
    ("Author intent is one factor in interpretation but the text itself generates meaning independently.","important_point"),

    # ── GEOGRAPHY & ENVIRONMENT ──────────────────────────────────
    ("Climate is the long-term pattern of weather in a region over decades.","definition"),
    ("Weather is the short-term state of the atmosphere at a specific time and place.","definition"),
    ("A biome is a large community of plants and animals occupying a major habitat.","definition"),
    ("The greenhouse effect warms Earth's surface when atmospheric gases trap outgoing heat.","definition"),
    ("Deforestation is the permanent removal of forests for agriculture, logging, or development.","definition"),
    ("The water cycle describes the continuous movement of water through evaporation, condensation, and precipitation.","definition"),
    ("Tectonic plates are massive segments of Earth's crust that move and interact.","definition"),
    ("Biodiversity is the variety of life on Earth including genetic, species, and ecosystem diversity.","definition"),

    ("Ocean currents regulate global climate by distributing heat around the planet.","concept"),
    ("The carbon cycle moves carbon between the atmosphere, biosphere, oceans, and geosphere.","concept"),
    ("Urbanization concentrates populations in cities creating both economic growth and environmental pressures.","concept"),

    ("The Amazon rainforest produces about 20% of Earth's oxygen and hosts immense biodiversity.","example"),
    ("The 1986 Chernobyl disaster demonstrated the long-term environmental impact of nuclear accidents.","example"),
    ("Coral reef bleaching is caused by elevated ocean temperatures disrupting the symbiotic algae.","example"),

    ("Climate change is accelerated by human emissions of greenhouse gases primarily carbon dioxide.","important_point"),
    ("Biodiversity loss is irreversible once a species goes extinct and threatens ecosystem stability.","important_point"),
    ("Sustainable development meets present needs without compromising future generations' ability to meet theirs.","important_point"),

    # ── ENGINEERING ──────────────────────────────────────────────
    ("Stress is the internal force per unit area within a material resisting external loads.","definition"),
    ("Strain is the deformation of a material per unit length in response to applied stress.","definition"),
    ("A circuit is a closed loop through which electric current can flow.","definition"),
    ("Impedance is the total opposition a circuit presents to alternating current.","definition"),
    ("Thermodynamics studies the relationships between heat, work, and energy in systems.","definition"),
    ("Signal processing analyzes and modifies signals to extract information or remove noise.","definition"),
    ("Control systems use feedback to maintain desired outputs despite disturbances.","definition"),
    ("Structural integrity is the ability of a structure to withstand loads without failure.","definition"),

    ("The feedback control loop continuously measures output and adjusts input to reach the target.","concept"),
    ("Hooke's law states that stress is proportional to strain within a material's elastic limit.","concept"),
    ("Kirchhoff's laws govern voltage and current relationships in electrical circuits.","concept"),

    ("The Tacoma Narrows Bridge collapsed in 1940 due to resonance from wind-induced oscillation.","example"),
    ("Silicon semiconductors enabled transistors replacing vacuum tubes in computers in the 1950s.","example"),
    ("PID controllers are used in industrial processes to maintain temperature, speed, or pressure.","example"),

    ("Safety factors must be applied in structural design to account for material variability and uncertainty.","important_point"),
    ("Prototype testing is essential before deploying engineering solutions at scale.","important_point"),
    ("Interdisciplinary collaboration is required for solving complex modern engineering challenges.","important_point"),
]