# -*- coding: utf-8 -*-
"""Train Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtmOi_QgDaoEJ2e31QveIIdOIeMMYngI
"""

# models/train_all.py
# Run: python -m models.train_all

"""
Master Training Script
-----------------------
Trains ANN, CNN, and LSTM, then compares their performance.
Run this once to train all models and see the comparison table.
"""

from models.data_prep  import prepare_dataset
from models.ann_model  import train_ann,  save_model as save_ann
from models.cnn_model  import train_cnn
from models.lstm_model import train_lstm
from models.evaluator  import evaluate_model, compare_models
import torch, os


def main():
    print("\n🚀 Starting model training pipeline...\n")

    # ── Step 1: Prepare data ──────────────────────────────────────
    X_train, X_val, X_test, y_train, y_val, y_test = prepare_dataset()

    # ── Step 2: Train all 3 models ────────────────────────────────
    ann_model,  _, _ = train_ann(X_train, y_train, X_val, y_val, epochs=50)
    cnn_model,  _, _ = train_cnn(X_train, y_train, X_val, y_val, epochs=50)
    lstm_model, _, _ = train_lstm(X_train, y_train, X_val, y_val, epochs=50)

    # ── Step 3: Evaluate on test set ──────────────────────────────
    print("\n\n📊 EVALUATING ON TEST SET...")
    ann_results  = evaluate_model(ann_model,  X_test, y_test, "ANN")
    cnn_results  = evaluate_model(cnn_model,  X_test, y_test, "CNN")
    lstm_results = evaluate_model(lstm_model, X_test, y_test, "LSTM")

    # ── Step 4: Compare all models ────────────────────────────────
    compare_models({
        "ANN" : ann_results,
        "CNN" : cnn_results,
        "LSTM": lstm_results
    })

    # ── Step 5: Save models ───────────────────────────────────────
    os.makedirs("models/saved", exist_ok=True)
    torch.save(ann_model.state_dict(),  "models/saved/ann_model.pt")
    torch.save(cnn_model.state_dict(),  "models/saved/cnn_model.pt")
    torch.save(lstm_model.state_dict(), "models/saved/lstm_model.pt")
    print("\n✅ All models saved to models/saved/")


if __name__ == "__main__":
    main()